### Welcome to the config of the VoteDay plugin
### Author: Ksio

# A player is eligable to vote if the player:
# - Is not in The End or Nether
# - The time is night (between 0 and 12000 ingame ticks)

#This section is for general vote settings
vote:
    # This represents which percentage of the eligable players need to vote in order for the vote to pass. Accepts decimal point numbers. Default is 50%
    percentage: 50
    # This is how long a vote lasts in ticks. 20 ticks = one second
    duration: 1200

# This setting enables the timelapse animation. Do note that this can lag the server. You can change the animation settings to your liking or just leave them at default values
# Default: disabled
dayAnimation:
    enabled: false
    # How much time will be added every <tick_delay> ticks
    time_step: 400
    # How often the task to add time is called
    tick_delay: 1
    
# This section is for the boss bar
# Default: enabled
bossBar:
    # Changing this may require a full restart
    enabled: true
    # The name of the boss bar. See messages.yml for more info on color coding strings
    name: "&6Vote for day"
    # The color of the boss bar. Accepted values: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
    color: YELLOW
    # The style of the boss bar. Accepted values: SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20, SOLID
    style: SEGMENTED_10