name: VoteDay
author: Ksio
main: ksio.voteday.main.VoteDay
version: 1.1.0
api-version: 1.15
commands:
 voteday:
  description: Vote to bring the sun out
  usage: Something went wrong, please use /voteday help
  aliases: vd
permissions:
  voteday.reload:
   description: These players can reload the VoteDay config
   default: op
  voteday.*:
   description: Wildcard permission
   default: op
   children:
     voteday.reload: true